# Generated by Django 3.2.7 on 2021-09-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование задачи')),
                ('ip_range', models.CharField(max_length=200, verbose_name='Диапазон адресов')),
                ('result', models.TextField(verbose_name='Результат работы задачи')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('started', 'Запущен'), ('stopped', 'Остановлен'), ('finished', 'Выполнен')], default='created', max_length=100, verbose_name='Текущий статус задачи')),
            ],
        ),
    ]
